name: Publish to Catalog

on:
  release:
    types: [published]

jobs:
  publish-staging:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Build
        run: npm run build

      - name: Publish to Staging Catalog
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID_PRE }}
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID_PRE }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN_PRE }}
        run: node --experimental-strip-types scripts/sync-to-kv.ts

  publish-production:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Run Build
        run: npm run build

      - name: Publish to Production Catalog
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: node --experimental-strip-types scripts/sync-to-kv.ts
